version: 2.1
commands:
  conclave_build:
    description: 'Build Conclave'
    parameters:
      env:
        type: string
        default: "dev"
    steps:
      - run: npm install

      - run: npm run build
  conclave_process:
    description: 'Build and test'
    parameters:
      env:
        type: string
        default: "dev"
    steps:
      - conclave_build:
          env: << parameters.env >>
      - run: npm run ci:test

jobs:
  build:
    docker:
      - image: circleci/node:12
      - image: postgres:9.6.6-alpine
        environment:
          POSTGRES_USER: dbuser
          POSTGRES_DB: dbuser
          POSTGRES_PASSWORD: dbpassword_password
    working_directory: ~/conclave

    steps:
      - checkout
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgress && exit 1
      - conclave_process:
          env: "prod"



